# Generated by Django 5.2.6 on 2025-09-08 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='doctors_app_status_1a9da5_idx',
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'status'], name='doctors_app_doctor__be8b76_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='doctors_app_patient_2193e0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appointment_date'], name='doctors_app_status_47b711_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date', 'appointment_time'], name='doctors_app_doctor__16758c_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty', 'is_available'], name='doctors_doc_special_44a0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['state', 'is_available'], name='doctors_doc_state_a0d8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['consultation_fee'], name='doctors_doc_consult_9e9809_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['experience_years'], name='doctors_doc_experie_6b5416_idx'),
        ),
    ]
