# Generated by Django 5.2.6 on 2025-09-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctoreducation_doctorspecialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('general', 'General Medicine'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose, Throat)'), ('gynecology', 'Gynecology'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('respiratory', 'Pulmonology'), ('gastroenterology', 'Gastroenterology'), ('endocrinology', 'Endocrinology'), ('urology', 'Urology'), ('oncology', 'Oncology'), ('rheumatology', 'Rheumatology'), ('anesthesiology', 'Anesthesiology'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('emergency', 'Emergency Medicine')], db_index=True, help_text="Doctor's medical specialty", max_length=50),
        ),
    ]
