# Generated by Django 5.2.6 on 2025-09-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('office', "Pay at Doctor's Office"), ('insurance', 'Insurance Coverage')], default='office', help_text='How the patient will pay for the appointment', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Additional payment-related notes'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('cancelled', 'Payment Cancelled'), ('refunded', 'Payment Refunded')], default='pending', help_text='Current payment status', max_length=20),
        ),
    ]
